spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hotdeal
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
my-values:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
  ppomppu:
    url:
      list: https://m.ppomppu.co.kr/new/bbs_list.php?id=%s&page=%d
      view: https://m.ppomppu.co.kr/new/bbs_view.php?id=%s&no=%d
    param:
      domestic: ppomppu
      overseas: ppomppu4
  dealbada:
    url:
      list: http://www.dealbada.com/bbs/board.php?bo_table=%s&page=%d
      view: http://www.dealbada.com/bbs/board.php?bo_table=%s&wr_id=%d
    param:
      domestic: deal_domestic
      overseas: deal_oversea
  clien:
    url:
      list: https://m.clien.net/service/board/%s?po=%d # 0부터 시작하는것이 특이점
      view: https://m.clien.net/service/board/%s/%d
    param:
      thrifty: jirum
  coolenjoy:
    url:
      list: http://www.coolenjoy.net/bbs/%s/p%d
      view: http://www.coolenjoy.net/bbs/%s/%d
    param:
      thrifty: jirum

