spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hotdeal
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  #        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
ppomppu:
  url:
    list: http://m.ppomppu.co.kr/new/bbs_list.php?id=%s&page=%d
    view: http://m.ppomppu.co.kr/new/bbs_view.php?id=%s&no=%d
  param:
    domestic: ppomppu
    overseas: ppomppu4


